use UNIVER_lab4
SELECT FACULTY.FACULTY,PULPIT.PULPIT,GROUPS.PROFESSION,SUBJECT.SUBJECT,STUDENT.NAME,PROGRESS.NOTE,
Case
When (PROGRESS.NOTE = 8) THEN 'Восемь'
When (PROGRESS.NOTE = 7) THEN 'Семь'
When (PROGRESS.NOTE = 6) THEN 'Шесть'
end Оценка
  FROM ((((((PROGRESS INNER JOIN STUDENT
    ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT)
    INNER JOIN GROUPS ON  STUDENT.IDGROUP = GROUPS.IDGROUP)
	INNER JOIN PROFESSION ON PROFESSION.PROFESSION = GROUPS.PROFESSION)
    INNER JOIN  FACULTY ON FACULTY.FACULTY = PROFESSION.FACULTY)
    INNER JOIN  PULPIT ON FACULTY.FACULTY = PULPIT.FACULTY)
    INNER JOIN SUBJECT ON PULPIT.PULPIT = SUBJECT.PULPIT)
WHERE (PROGRESS.NOTE BETWEEN 6 AND 8)   
ORDER BY
(Case
when(PROGRESS.NOTE=6) then 3
when(PROGRESS.NOTE=7) then 1
when(PROGRESS.NOTE=8) then 2
end
)