use UNIVER_lab4
SELECT PULPIT.PULPIT_NAME, isnull(TEACHER.TEACHER_NAME,'***')[TEACHER_NAME]
FROM TEACHER Left Outer JOIN  PULPIT
ON PULPIT.PULPIT=TEACHER.PULPIT

use UNIVER_lab4
SELECT PULPIT.PULPIT_NAME, isnull(TEACHER.TEACHER_NAME,'***')[TEACHER_NAME]
FROM PULPIT Right Outer JOIN TEACHER
ON PULPIT.PULPIT=TEACHER.PULPIT