use UNIVER_lab4
--Коммутативность OUTER JOIN: результирующий набор не зависит от порядка, в котором указаны исходные таблицы.
SELECT * 
FROM PULPIT FULL OUTER JOIN  TEACHER
ON PULPIT.PULPIT = TEACHER.PULPIT
WHERE TEACHER_NAME IS NULL

SELECT * 
FROM TEACHER FULL OUTER JOIN  PULPIT
ON PULPIT.PULPIT = TEACHER.PULPIT
WHERE TEACHER_NAME IS NULL

--1 содержит данные левой (в операции FULL OUTER JOIN) и не содержит данные правой
SELECT *
FROM PULPIT FULL OUTER JOIN TEACHER 
ON PULPIT.PULPIT = TEACHER.PULPIT
WHERE TEACHER_NAME IS NULL
ORDER BY PULPIT_NAME,FACULTY

--2 содержит данные правой таблицы и не содержащие данные левой
SELECT PULPIT.PULPIT,PULPIT.PULPIT_NAME,PULPIT.FACULTY 
FROM TEACHER  RIGHT OUTER JOIN  PULPIT 
ON PULPIT.PULPIT = TEACHER.PULPIT
WHERE TEACHER_NAME IS NULL
    

--3 содержит данные правой таблицы и левой
SELECT PULPIT.PULPIT,PULPIT.PULPIT_NAME,PULPIT.FACULTY, TEACHER.TEACHER_NAME 
FROM PULPIT FULL OUTER JOIN TEACHER 
ON PULPIT.PULPIT = TEACHER.PULPIT
WHERE TEACHER_NAME IS NOT NULL
ORDER BY PULPIT_NAME,FACULTY