use UNIVER_lab4
SELECT AUDITORIUM_TYPE.AUDITORIUM_TYPENAME, AUDITORIUM.AUDITORIUM
FROM AUDITORIUM_TYPE, AUDITORIUM
WHERE AUDITORIUM_TYPE.AUDITORIUM_TYPE = AUDITORIUM.AUDITORIUM_TYPE

SELECT T1.AUDITORIUM_TYPENAME, T2.AUDITORIUM
FROM AUDITORIUM_TYPE AS T1, AUDITORIUM AS T2
WHERE T1.AUDITORIUM_TYPE = T2.AUDITORIUM_TYPE