--use UNIVER_lab4 
--SELECT  AUDITORIUM.AUDITORIUM_CAPACITY, AUDITORIUM.AUDITORIUM_TYPE
--FROM AUDITORIUM
--where AUDITORIUM.AUDITORIUM_CAPACITY=(select top(1) AUDITORIUM_CAPACITY 
--													From AUDITORIUM
--													where AUDITORIUM.AUDITORIUM_TYPE=AUDITORIUM.AUDITORIUM_TYPE 
--													order by AUDITORIUM_CAPACITY desc)

use UNIVER_lab4
SELECT  AUDITORIUM_CAPACITY, AUDITORIUM_TYPE
FROM AUDITORIUM a
where AUDITORIUM_CAPACITY=(select top(1) AUDITORIUM_CAPACITY 
								from AUDITORIUM aa
								where aa.AUDITORIUM_TYPE=a.AUDITORIUM_TYPE 
								order by AUDITORIUM_CAPACITY desc)