USE UNIVER_lab4
SELECT TOP 1 (SELECT AVG(NOTE) from PROGRESS
				WHERE SUBJECT LIKE 'нюХо')[нюХо],
			 (SELECT AVG(NOTE) from PROGRESS
				WHERE SUBJECT LIKE 'йц')[йц],
			 (SELECT AVG(NOTE) from PROGRESS
				WHERE SUBJECT LIKE 'ясад')[ясад]
FROM PROGRESS

