SELECT  FACULTY.FACULTY_NAME [‘¿ ”À‹“≈“],
		GROUPS.PROFESSION [—œ≈÷»¿À‹ÕŒ—“‹],
		STUDENT.IDGROUP [√–”œœ¿],
		ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(2))), 2) [—–≈ƒÕﬂﬂ Œ÷≈Õ ¿]
FROM FACULTY INNER JOIN GROUPS 
ON FACULTY.FACULTY=GROUPS.FACULTY
INNER JOIN STUDENT 
ON GROUPS.IDGROUP=STUDENT.IDGROUP
INNER JOIN PROGRESS
ON PROGRESS.IDSTUDENT=STUDENT.IDSTUDENT
GROUP BY FACULTY.FACULTY_NAME,
GROUPS.PROFESSION,
STUDENT.IDGROUP
ORDER BY [—–≈ƒÕﬂﬂ Œ÷≈Õ ¿] Desc 


SELECT  FACULTY.FACULTY_NAME [‘¿ ”À‹“≈“],
		GROUPS.PROFESSION [—œ≈÷»¿À‹ÕŒ—“‹],
		STUDENT.IDGROUP [√–”œœ¿],
		ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(2))), 2) [—–≈ƒÕﬂﬂ Œ÷≈Õ ¿]
FROM FACULTY INNER JOIN GROUPS 
ON FACULTY.FACULTY=GROUPS.FACULTY
INNER JOIN STUDENT 
ON GROUPS.IDGROUP=STUDENT.IDGROUP
INNER JOIN PROGRESS
ON PROGRESS.IDSTUDENT=STUDENT.IDSTUDENT
WHERE PROGRESS.SUBJECT='¡ƒ' or PROGRESS.SUBJECT='Œ¿Ëœ'
GROUP BY FACULTY.FACULTY_NAME,
GROUPS.PROFESSION,
STUDENT.IDGROUP
ORDER BY [—–≈ƒÕﬂﬂ Œ÷≈Õ ¿] Desc 