SELECT  GROUPS.PROFESSION [—œ≈÷»¿À‹ÕŒ—“‹],
		PROGRESS.SUBJECT [ƒ»—÷»œÀ»Õ¿],
		ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(2))), 2) [—–≈ƒÕﬂﬂ Œ÷≈Õ ¿]
FROM STUDENT INNER JOIN GROUPS 
ON STUDENT.IDGROUP=GROUPS.IDGROUP
INNER JOIN PROGRESS 
ON  PROGRESS.IDSTUDENT=STUDENT.IDSTUDENT
WHERE GROUPS.FACULTY='»“'
GROUP BY CUBE (
GROUPS.PROFESSION,
PROGRESS.SUBJECT)