SELECT GROUPS.FACULTY [‘¿ ”À‹“≈“], 
GROUPS.PROFESSION [—œ≈÷»¿À‹ÕŒ—“‹],
PROGRESS.SUBJECT [ƒ»—÷»œÀ»Õ¿],
round(avg(cast(PROGRESS.NOTE as float(4))), 2) [—–≈ƒÕﬂﬂ Œ÷≈Õ ¿]
FROM GROUPS Inner Join STUDENT
On GROUPS.IDGROUP=STUDENT.IDGROUP
Inner Join PROGRESS 
On STUDENT.IDSTUDENT=PROGRESS.IDSTUDENT
Where GROUPS.FACULTY='»“'
Group BY GROUPS.FACULTY,
GROUPS.PROFESSION,
PROGRESS.SUBJECT
INTERSECT
SELECT GROUPS.FACULTY [‘¿ ”À‹“≈“], 
GROUPS.PROFESSION [—œ≈÷»¿À‹ÕŒ—“‹],
PROGRESS.SUBJECT [ƒ»—÷»œÀ»Õ¿],
round(avg(cast(PROGRESS.NOTE as float(4))), 2) [—–≈ƒÕﬂﬂ Œ÷≈Õ ¿]
FROM GROUPS Inner Join STUDENT
On GROUPS.IDGROUP=STUDENT.IDGROUP
Inner Join PROGRESS 
On STUDENT.IDSTUDENT=PROGRESS.IDSTUDENT
Where GROUPS.FACULTY='’“Ë“'
Group BY GROUPS.FACULTY,
GROUPS.PROFESSION,
PROGRESS.SUBJECT